### PR TITLE
fixes to run the nim game

### PR DESCRIPTION
**Pull request by namin**

### CODE REVIEW

**Comment by npe9** [comment]
Thank you for this!

I just noticed you do PL work and just moved to Harvard. Do you interact with the MIT verified systems group (Chlipala, Kaashoek, Zedovich) at all?

**Comment by namin** [comment]
Thanks for this repo :)

Yes, I do interact informally. Specially Adam Chlipala these days. :) And Kaashoek was my undergraduate advisor when I was at MIT :D I plan to attend https://svd.csail.mit.edu/2019/ if I am around then.

**Comment by npe9** [comment]
Small world, see you there.

**Comment by namin** [comment]
👍

**Pull request merged**
